Feature/analyses
pr0gen/stratego pull request #97
Opened 2021-02-16 08:40 UTC by qroyer

2021-02-16 09:01 UTC, Rolf1e requested changes
Remove `ai_python/src/__init__.pyc`

2021-02-16 09:01 UTC, Rolf1e commented on ai_python/src/analyses.py
> +plot_victories(sys.argv[1])
Ca doit pas etre la ca si ?

2021-02-16 09:25 UTC, qroyer commented on ai_python/src/analyses.py
> +plot_victories(sys.argv[1])
yep c'est ok , 
et j'ai dynamisé le namefile du png car je viens de voir que SimpleBar.png peut poser probleme en cas de plusieurs executions

2021-02-16 09:34 UTC, Rolf1e commented
La cicd python passe pas par contre @qroyer

2021-02-16 23:00 UTC, Rolf1e commented
Plot tests doesnot work :(

2021-02-17 12:39 UTC, Rolf1e approved these changes

2021-02-17 12:39 UTC, merged